import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Values from Firebase console (project johnfood-b281a).
/// These are public client keys, safe to commit. Real secrets
/// (service account JSON) live only in GitHub Secrets.
/// Generated by hand; prefer `flutterfire configure` for production.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD09MUFhaHlQBnkFmxELzqAZij0EYw1jX4',
    appId: '1:738831913873:web:7082bed270b4e786bbc030',
    messagingSenderId: '738831913873',
    projectId: 'johnfood-b281a',
    authDomain: 'johnfood-b281a.firebaseapp.com',
    storageBucket: 'johnfood-b281a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpgnRP0WI80HxiwM31YonaNk1wcWvXhNI',
    appId: '1:738831913873:android:54716c856810e32abbc030',
    messagingSenderId: '738831913873',
    projectId: 'johnfood-b281a',
    storageBucket: 'johnfood-b281a.firebasestorage.app',
  );

  // No iOS app registered yet. Register one in the Firebase console
  // (bundle id com.merjdev.johnfoods) and fill these in before building for iPhone.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'johnfood-b281a',
    storageBucket: 'johnfood-b281a.firebasestorage.app',
    iosBundleId: 'com.merjdev.johnfoods',
  );
}
