/* John Foods menu data. Mirrors lib/data/sample_data.dart.
   Prices in Philippine peso. No emoji. */
const CATEGORIES = [
  { id: "burgers", name: "Burgers" },
  { id: "pizza", name: "Pizza" },
  { id: "chicken", name: "Chicken" },
  { id: "rice", name: "Rice Meals" },
  { id: "pasta", name: "Pasta" },
  { id: "drinks", name: "Drinks" },
  { id: "desserts", name: "Desserts" },
  { id: "snacks", name: "Snacks" }
];

const FOODS = [
  { id: "b1", name: "Classic Beef Burger", price: 120, rating: 4.6, time: "20 min", cat: "burgers", img: "assets/b1.jpg" },
  { id: "b2", name: "Cheese Burger", price: 135, rating: 4.7, time: "20 min", cat: "burgers", img: "assets/b2.jpg" },
  { id: "b3", name: "Double Patty Burger", price: 185, rating: 4.8, time: "25 min", cat: "burgers", img: "assets/b3.jpg" },
  { id: "b4", name: "Chicken Burger", price: 110, rating: 4.5, time: "20 min", cat: "burgers", img: "assets/b4.jpg" },
  { id: "b5", name: "Mushroom Burger", price: 125, rating: 4.4, time: "22 min", cat: "burgers", img: "assets/b5.jpg" },
  { id: "b6", name: "Bacon Cheeseburger", price: 165, rating: 4.7, time: "22 min", cat: "burgers", img: "assets/b6.jpg" },
  { id: "b7", name: "BBQ Burger", price: 150, rating: 4.6, time: "22 min", cat: "burgers", img: "assets/b7.jpg" },
  { id: "p1", name: "Pepperoni Pizza", price: 299, rating: 4.7, time: "30 min", cat: "pizza", img: "assets/p1.jpg" },
  { id: "p2", name: "Cheese Pizza", price: 249, rating: 4.5, time: "30 min", cat: "pizza", img: "assets/p2.jpg" },
  { id: "p3", name: "Hawaiian Pizza", price: 279, rating: 4.4, time: "30 min", cat: "pizza", img: "assets/p3.jpg" },
  { id: "p4", name: "Veggie Pizza", price: 259, rating: 4.3, time: "28 min", cat: "pizza", img: "assets/p4.jpg" },
  { id: "p5", name: "BBQ Chicken Pizza", price: 319, rating: 4.8, time: "32 min", cat: "pizza", img: "assets/p5.jpg" },
  { id: "p6", name: "Four Cheese Pizza", price: 329, rating: 4.7, time: "32 min", cat: "pizza", img: "assets/p6.jpg" },
  { id: "p7", name: "Meat Lovers Pizza", price: 339, rating: 4.8, time: "32 min", cat: "pizza", img: "assets/p7.jpg" },
  { id: "p8", name: "Burger Pizza", price: 349, rating: 4.9, time: "35 min", cat: "pizza", img: "assets/p8.jpg" },
  { id: "c1", name: "Fried Chicken 2pc", price: 149, rating: 4.7, time: "25 min", cat: "chicken", img: "assets/c1.jpg" },
  { id: "c2", name: "Chicken Tenders", price: 139, rating: 4.5, time: "22 min", cat: "chicken", img: "assets/c2.jpg" },
  { id: "c3", name: "Grilled Chicken", price: 159, rating: 4.6, time: "25 min", cat: "chicken", img: "assets/c3.jpg" },
  { id: "c4", name: "Chicken Wings", price: 169, rating: 4.6, time: "25 min", cat: "chicken", img: "assets/c4.jpg" },
  { id: "c5", name: "Chicken Popcorn", price: 99, rating: 4.4, time: "18 min", cat: "chicken", img: "assets/c5.jpg" },
  { id: "c6", name: "Spicy Chicken", price: 155, rating: 4.6, time: "25 min", cat: "chicken", img: "assets/c6.jpg" },
  { id: "c7", name: "Chicken Fillet", price: 145, rating: 4.5, time: "22 min", cat: "chicken", img: "assets/c7.jpg" },
  { id: "r1", name: "Chicken Adobo Meal", price: 120, rating: 4.8, time: "20 min", cat: "rice", img: "assets/r1.jpg" },
  { id: "r2", name: "Beef Tapa Meal", price: 130, rating: 4.7, time: "20 min", cat: "rice", img: "assets/r2.jpg" },
  { id: "r3", name: "Pork Sisig Meal", price: 135, rating: 4.7, time: "22 min", cat: "rice", img: "assets/r3.jpg" },
  { id: "r4", name: "Bangus Meal", price: 125, rating: 4.5, time: "20 min", cat: "rice", img: "assets/r4.jpg" },
  { id: "r5", name: "Tocino Meal", price: 115, rating: 4.6, time: "18 min", cat: "rice", img: "assets/r5.jpg" },
  { id: "r6", name: "Beef Steak Meal", price: 140, rating: 4.7, time: "22 min", cat: "rice", img: "assets/r6.jpg" },
  { id: "r7", name: "Fried Rice Meal", price: 125, rating: 4.6, time: "20 min", cat: "rice", img: "assets/r7.jpg" },
  { id: "pa1", name: "Spaghetti", price: 110, rating: 4.5, time: "20 min", cat: "pasta", img: "assets/pa1.jpg" },
  { id: "pa2", name: "Carbonara", price: 130, rating: 4.6, time: "22 min", cat: "pasta", img: "assets/pa2.jpg" },
  { id: "pa3", name: "Pesto Pasta", price: 140, rating: 4.4, time: "22 min", cat: "pasta", img: "assets/pa3.jpg" },
  { id: "pa4", name: "Baked Mac", price: 135, rating: 4.6, time: "25 min", cat: "pasta", img: "assets/pa4.jpg" },
  { id: "pa5", name: "Palabok", price: 120, rating: 4.7, time: "20 min", cat: "pasta", img: "assets/pa5.jpg" },
  { id: "pa6", name: "Shrimp Pasta", price: 155, rating: 4.7, time: "25 min", cat: "pasta", img: "assets/pa6.jpg" },
  { id: "pa7", name: "Tomato Basil Pasta", price: 125, rating: 4.5, time: "20 min", cat: "pasta", img: "assets/pa7.jpg" },
  { id: "d1", name: "Iced Coffee", price: 85, rating: 4.5, time: "10 min", cat: "drinks", img: "assets/d1.jpg" },
  { id: "d2", name: "Mango Shake", price: 95, rating: 4.7, time: "10 min", cat: "drinks", img: "assets/d2.jpg" },
  { id: "d3", name: "Lemonade", price: 65, rating: 4.4, time: "8 min", cat: "drinks", img: "assets/d3.jpg" },
  { id: "d4", name: "Milk Tea", price: 99, rating: 4.6, time: "12 min", cat: "drinks", img: "assets/d4.jpg" },
  { id: "d5", name: "Bottled Water", price: 30, rating: 4.2, time: "5 min", cat: "drinks", img: "assets/d5.jpg" },
  { id: "d6", name: "Strawberry Shake", price: 105, rating: 4.6, time: "10 min", cat: "drinks", img: "assets/d6.jpg" },
  { id: "d7", name: "Iced Tea", price: 60, rating: 4.3, time: "8 min", cat: "drinks", img: "assets/d7.jpg" },
  { id: "de1", name: "Halo Halo", price: 110, rating: 4.8, time: "15 min", cat: "desserts", img: "assets/de1.jpg" },
  { id: "de2", name: "Chocolate Cake", price: 95, rating: 4.7, time: "12 min", cat: "desserts", img: "assets/de2.jpg" },
  { id: "de3", name: "Leche Flan", price: 80, rating: 4.6, time: "12 min", cat: "desserts", img: "assets/de3.jpg" },
  { id: "de4", name: "Ice Cream Cup", price: 75, rating: 4.5, time: "10 min", cat: "desserts", img: "assets/de4.jpg" },
  { id: "de5", name: "Banana Cue", price: 45, rating: 4.4, time: "10 min", cat: "desserts", img: "assets/de5.jpg" },
  { id: "de6", name: "Ice Cream Cone", price: 55, rating: 4.5, time: "8 min", cat: "desserts", img: "assets/de6.jpg" },
  { id: "de7", name: "Brownie Sundae", price: 95, rating: 4.7, time: "12 min", cat: "desserts", img: "assets/de7.jpg" },
  { id: "s1", name: "French Fries", price: 75, rating: 4.5, time: "12 min", cat: "snacks", img: "assets/s1.jpg" },
  { id: "s2", name: "Nachos", price: 110, rating: 4.5, time: "15 min", cat: "snacks", img: "assets/s2.jpg" },
  { id: "s3", name: "Lumpia", price: 85, rating: 4.6, time: "15 min", cat: "snacks", img: "assets/s3.jpg" },
  { id: "s4", name: "Fish Balls", price: 55, rating: 4.3, time: "10 min", cat: "snacks", img: "assets/s4.jpg" },
  { id: "s5", name: "Garlic Bread", price: 65, rating: 4.4, time: "12 min", cat: "snacks", img: "assets/s5.jpg" },
  { id: "s6", name: "Loaded Fries", price: 95, rating: 4.6, time: "14 min", cat: "snacks", img: "assets/s6.jpg" },
  { id: "s7", name: "Onion Rings", price: 80, rating: 4.5, time: "12 min", cat: "snacks", img: "assets/s7.jpg" }
];

function peso(v) {
  return "PHP " + Number(v).toFixed(2);
}
